esphome:
  name: desk

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
 reboot_timeout: 0s

ota:
  password: !secret otapwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password



mqtt:
  broker: !secret mqttbroker
  username: !secret mqttuser
  password: !secret mqttpwd


  
switch:
  - platform: gpio
    name: "Desk Up"
    id: relay1
    interlock: [relay2]
    restore_mode: always off    
    pin: 
     number: "D3"
     inverted: yes
    
  - platform: gpio
    name: "Desk Down"
    id: relay2
    interlock: [relay1]
    restore_mode: always off
    pin: 
      number: "D4"  
      inverted: yes

binary_sensor:


  - platform: gpio
    id: open_button
    pin: 
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    name: "Button Up"

    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_multi_click:
      #Double Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
         - cover.control:
            id: desk_cover
            position: 60%

      #Single Click
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - cover.stop: desk_cover  
      #Hold
      - timing:
          - ON for at least 0.75s
        then:
          - cover.open: desk_cover
      #Release
      - timing:
          - ON for at least 1.0s
          - OFF for at least 0.1s
        then:
          - cover.stop: desk_cover


     
  - platform: gpio
    id: close_button
    pin: 
      number: D1
      mode: INPUT_PULLUP
      inverted: true
    name: "Button Down"

    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_multi_click:
      #Double Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
         - cover.control:
            id: desk_cover
            position: 0%

      #Single Click
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - cover.stop: desk_cover
  
      #Hold
      - timing:
          - ON for at least 0.75s
        then:
          - cover.close: desk_cover
      #Release
      - timing:
          - ON for at least 1.0s
          - OFF for at least 0.1s
        then:
          - cover.stop: desk_cover
       #Tripple Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
          - ON for at most 0.5s
          - OFF for at least 0.2s

        then:
          - homeassistant.service:
             service: light.toggle
             data:
               entity_id: light.schreibtischlampe_yeelight

sensor:
  - platform: template
    name: "Desk Hight"
    lambda: return id(desk_cover).position * 42 + 76.0;
    accuracy_decimals: 0
    unit_of_measurement: "cm"

cover:
- platform: time_based
  name: "Desk"
  command_topic: desk/cover/desk/command
  id: desk_cover
  open_action:
    - switch.turn_on: relay1
  open_duration: 14s
  close_action:
    - switch.turn_on: relay2

  close_duration: 14s
  stop_action:
    - switch.turn_off: relay1
    - switch.turn_off: relay2
