##helper

input_boolean:
  post_im_briefkasten:   
    name: Post im Briefkasten    
counter:
  post_im_briefkasten:    
    name: Post im Briefkasten    
    
    
    
    
    https://www.elanto24.de/schalterprogramme/busch-jaeger/busch-secureathome/zubehoer/36371/busch-jaeger-std-w5.11a-wassermelder-weiss
    
    
    
    
    https://www.voltus.de/sicherheitstechnik/o-o-4/abb-swm4-rn-wassermelder-fuer-12v.html#
    
    
    Länge: 210 cm Tiefe: 25 cm